### ISSUE TITLE
Duplicate "package manage" permission in v.1.0.0

### ISSUE THREAD

**Issue by 0dysseas** [canonical/surl#49] opened 2022-12-08 09:34 UTC
The "package manage" permission is listed 2 times as `package_manage` and `package-manage` in the list of available permissions:
```
$ surl -h
[rest of options omitted for brevity]  
-p {edit_account,modify_account_key,package_access,**package_manage**,package_metrics,package_push,package_purchase,package_register,package_release,package_update,package_upload,package_upload_request,store_admin,store_review,account-register-package,account-view-packages,**package-manage**,package-manage-acl,package-manage-metadata,package-manage-releases,package-manage-revisions,package-view,package-view-acl,package-view-metadata,package-view-metrics,package-view-releases,package-view-revisions},  
--permission {edit_account,modify_account_key,package_access,**package_manage**,package_metrics,package_push,package_purchase,package_register,package_release,package_update,package_upload,package_upload_request,store_admin,store_review,account-register-package,account-view-packages,**package-manage**,package-manage-acl,package-manage-metadata,package-manage-releases,package-manage-revisions,package-view,package-view-acl,package-view-metadata,package-view-metrics,package-view-releases,package-view-revisions}
```
This is confusing because if they are indeed different and used for different reasons, there's no explanation what's the purpose of each one. I believe there should, at least, be a relevant doc entry listing them per supported back-end (e.g. SCA, charmhub).

**Comment by shanepelletier** [comment] 2023-02-22 13:16
I'm closing this and rolling it into the main "this thing needs docs" issue (#47) for easier tracking; I may reopen this later if I decide that the issue isn't docs related (e.g., perhaps just merging the two `package_manage` permissions, or somehow labelling them as being related to different stores).

**Closed by shanepelletier** 2023-02-22 13:16 UTC
